# Generated by Django 2.1.2 on 2018-10-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='id',
        ),
        migrations.AddField(
            model_name='results',
            name='trackId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Competition.Tracks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracks',
            name='trackId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
