# Generated by Django 2.2.7 on 2019-11-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competition', '0004_auto_20191116_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='current_record',
            field=models.CharField(max_length=50),
        ),
    ]
